# Generated by Django 4.0.5 on 2022-06-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=28)),
                ('tamanho', models.CharField(max_length=5)),
                ('qtd', models.CharField(max_length=100)),
            ],
        ),
    ]
