# Generated by Django 4.0.5 on 2022-06-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nota_fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('endereço', models.CharField(max_length=50)),
                ('transportadora', models.CharField(max_length=50)),
                ('num_serie', models.CharField(max_length=50)),
            ],
        ),
    ]
