# Generated by Django 4.0.5 on 2022-06-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=13)),
                ('tel', models.CharField(max_length=13)),
                ('mail', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
            ],
        ),
    ]
